version: '3.9'

services:
  proxy:
    build:
      context: ./images/proxy
    restart: always
    ports:
      - "80:80"
      - "4242:4242"
    networks:
      - frontend
      - backend
    depends_on:
      - compute
      - web
    
  redis:
    image: "redis:alpine"  # You can specify another version if needed
    restart: always
    volumes:
      - './images/web/data/redis:/data'
    networks:
      - backend

  web:
    build:
      context: .
      dockerfile: ./images/web/Dockerfile
    env_file: .env
    depends_on:
      - dizzy_base
      - redis
    volumes:
      - './images/web/app:/app:ro' # Should be dev only (and maybe move django db to data)
      - './images/web/data:/data'
      - './shared_data:/data/shared'
    networks:
      - backend

  compute:
    build:
      context: .
      dockerfile: ./images/compute/Dockerfile
      args:
        COMPUTE_EXTRA_BASE: "${COMPUTE_EXTRA_BASE}"
    restart: always
    env_file: .env
    depends_on:
      - dizzy_base
      - redis
    volumes:
      - './images/compute/app:/app:ro' # Should be dev only
      - './images/compute/data:/data'
      - './shared_data:/data/shared'
    networks:
      - backend

  dizzy_base:
    build:
      context: .
      dockerfile: ./images/dizzy_base/Dockerfile.dizzy_dev
    env_file: .env


networks:
  frontend:
  backend: 
