version: '3.9'

services:

  web:
    build:
      context: ./images/web
    env_file: .env
    volumes:
      - './images/web/app:/app:ro' # Should be dev only (and maybe move django db to data)
      - './images/web/data:/data'
    networks:
      - rpc-net
    ports:
      - 80:8000

  compute:
    build:
      context: ./images/compute
      args:
        COMPUTE_EXTRA_BASE: "${COMPUTE_EXTRA_BASE:-python:3.10}"
    env_file: .env
    volumes:
      - './images/compute/app:/app:ro' # Should be dev only
      - './images/compute/data:/data'
    networks:
      - rpc-net

networks:
  rpc-net:
    driver: bridge
