version: '3.9'

services:
  redis:
    image: "redis:alpine"  # You can specify another version if needed
    restart: always
    volumes:
      - './images/web/data/redis:/data'
    networks:
      - rpc-net

  web:
    build:
      context: .
      dockerfile: ./images/web/Dockerfile
    env_file: .env
    volumes:
      - './images/web/app:/app:ro' # Should be dev only (and maybe move django db to data)
      - './images/web/data:/data'
      - './shared_data:/data/shared'
    networks:
      - rpc-net
    ports:
      - 80:8000

  compute:
    build:
      context: .
      dockerfile: ./images/compute/Dockerfile
      args:
        COMPUTE_EXTRA_BASE: "${COMPUTE_EXTRA_BASE}"
    env_file: .env
    volumes:
      - './images/compute/app:/app:ro' # Should be dev only
      - './images/compute/data:/data'
      - './shared_data:/data/shared'
    networks:
      - rpc-net

networks:
  rpc-net:
    driver: bridge