version: '3.9'
services:
  dizzy_base:
    build:
      context: .
      dockerfile: ./images/dizzy_base/Dockerfile.dizzy_dev
    image: dazzle-dizzy_base
    env_file: .env
    networks:
      - backend

  web:
    build:
      context: .
      dockerfile: ./images/web/Dockerfile
    image: dazzle-web
    env_file: .env
    depends_on:
      - dizzy_base
      - redis
    volumes:
      - './images/web/app:/app:ro'
      - './images/web/data:/data'
      - './shared:/data/shared'
    networks:
      - backend

  compute:
    build:
      context: .
      dockerfile: ./images/compute/Dockerfile
      args:
        COMPUTE_EXTRA_BASE: "${COMPUTE_EXTRA_BASE:-python:3.12}"
    image: dazzle-compute
    restart: always
    env_file: .env
    depends_on:
      - dizzy_base
      - redis
    volumes:
      - './images/compute/app:/app:ro'
      - './images/compute/data:/data'
      - './shared:/data/shared'
    networks:
      - backend

  proxy:
    build:
      context: ./images/proxy
    restart: always
    ports:
      - "80:80"
    networks:
      - frontend
      - backend
    depends_on:
      - compute
      - web
    volumes:
      - './proxy/logs:/var/log/nginx'

  redis:
    image: "redis:alpine"
    restart: always
    volumes:
      - './images/web/data/redis:/data'
    networks:
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    internal: true