version: '3.8'

services:

  web:
    build:
      context: ./images/web
    image: web
    env_file: .env
    volumes:
      - ./images/web/data:/app/data
    networks:
      - rpc-net
    ports:
      - 8000:8000

  compute:
    build:
      context: ./images/compute
    image: compute
    env_file: .env
    volumes:
      - ./images/compute/data:/app/data
    networks:
      - rpc-net

networks:
  rpc-net:
    driver: bridge
