version: '3.9'
# Don't forget to set DJANGO_SECRET_KEY in your environment.
# You can set .env, but you really should just set it in your environment.
# Ex. `DJANGO_SECRET_KEY=your_secret_key ./run.sh -p`
services:
  web:
    environment:
    - WEB_PRODUCTION='True'
    - DJANGO_SECRET_KEY='${DJANGO_SECRET_KEY}' 
    - DIZZY_LOG_LEVEL='INFO'
    - N_WEBWORKERS=4
    command: gunicorn --config python:dazzlesite.gunicorn dazzlesite.asgi:application -k uvicorn.workers.UvicornWorker -b $DJANGO_PRIMARY_HOST:8000
  dizzy_base:
    build:
      context: .
      dockerfile: ./images/dizzy_base/Dockerfile.dizzy_prod
    env_file: .env