# Use NVIDIA's CUDA base image
FROM nvidia/cuda:12.2.2-cudnn8-runtime-ubuntu22.04
FROM python:3.10

WORKDIR /app

# Install Python and other dependencies
RUN apt-get update && apt-get install -y python3.10 python3-pip

# Copy requirements and install Python packages
COPY ./requirements.txt .
RUN pip3 install --no-cache-dir -r requirements.txt

# Set environment variable (as in your original Dockerfile)
ENV DIZZY_DATA_ROOT="/data/.dizzy"

CMD [ "python3", "dizzy_server.py"]
