name: Docker Compose Actions Workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: bash ./run.sh -d -e
      - name: Test
        run: |
          curl -s "localhost:8000/dizzy/?entity=einz&workflow=einzy" | sed "s/'/\"/g" | jq -e
