name: Docker Compose Actions Workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Ensure submodules are checked out

      - name: Initialize Submodules
        run: |
          git submodule sync
          git submodule update --init --recursive

      - name: Build the stack
        run: bash ./run -d -e
      - name: Test
        run: |
          curl -s "localhost/dizzy/?entity=einz&workflow=einzy" | sed "s/'/\"/g" | jq -e
