name: Docker Compose Actions Workflow

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Initialize Submodules
        run: |
          git submodule sync
          git submodule update --init --recursive

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      # Build base image first
      - name: Build dazzle
        run: ./run -d -e

      - name: Wait for services
        run: |
          timeout 60s bash -c 'while ! curl -s http://localhost/ >/dev/null; do sleep 1; done'

      - name: Test
        run: |
          curl -s "localhost/dizzy/?entity=einz&workflow=einzy" | sed "s/'/\"/g" | jq -e

      - name: Logs on failure
        if: failure()
        run: |
          echo "Docker images:"
          docker images
          echo "Docker compose ps:"
          docker compose ps
          echo "Docker compose logs:"
          docker compose logs