name: Docker Compose Actions Workflow

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Updated to v4
        with:
          submodules: true  # Ensure submodules are checked out
      
      - name: Initialize Submodules
        run: |
          git submodule sync
          git submodule update --init --recursive

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true  # This ensures docker buildx is available

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      # No need for docker-compose alias as modern Ubuntu comes with docker compose v2
      
      - name: Build and start services
        run: bash ./run -d -e
        env:
          DOCKER_BUILDKIT: 1
          COMPOSE_DOCKER_CLI_BUILD: 1
          
      - name: Wait for services to be ready
        run: |
          # Wait for the web service to be ready (adjust timeout as needed)
          timeout 60s bash -c 'while ! curl -s http://localhost/health >/dev/null; do sleep 1; done'
        
      - name: Test
        run: |
          curl -s "localhost/dizzy/?entity=einz&workflow=einzy" | sed "s/'/\"/g" | jq -e
        
      - name: Docker logs on failure
        if: failure()
        run: |
          docker compose ps
          docker compose logs